version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BOT_ID=${BOT_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - TOKEN=${TOKEN}
      - SUBMISSION_CHANNEL_ID=${SUBMISSION_CHANNEL_ID}
      - VOTE_CHANNEL_ID=${VOTE_CHANNEL_ID}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
